(if (eq? $WRITING_ROOT (nil)) (abort "Please set the WRITING_ROOT environment variable!"))

(set $lpsources (' index.lp 01-first.lp 02-second.lp 03-third.lp))
(set $zones     (empty))
(set $top       (false))

(include do $WRITING_ROOT/Build/rules/standard-driver)

